### PR TITLE
Try with --color=16m

### PR DESCRIPTION
**Pull request by cotsog**

### CODE REVIEW

**Comment by Berkmann18** [comment]
Thanks for the PR.
I'm pleased to see more test passing, I find it odd that the `Hello` logs are coloured as expected but some of the test cases still show up as uncoloured.
I tried with node v11.12 on both WSL (Ubuntu) and Git Bash but both print at least some coloured `Hello` properly while failing on respectively other tests or on the same + others.

@nazrhyn @Qix- Any ideas?

I'm tempted to just drop the idea of switching to `chalk` but it offers a lot more colours and styles than `colors`.

**Comment by nazrhyn** [comment]
I wonder how easy it would be to just fork chalk and rip out the support detection.

**Comment by nazrhyn** [comment]
Coming back to this, since the revelations of https://github.com/chalk/chalk/pull/308, I've finally been able to revisit my tests for a helper function that uses chalk. Using the two properties together, I've been able to test both colored and un-colored in what seems to be a fairly deterministic fashion.

```js
beforeAll(function () {
	// For the uncolored tests, disable chalk via its API.
	chalk.enabled = false;
	chalk.level = 0;
});
```
```js
beforeAll(function () {
	// For the colored tests, enable chalk via its API.
	chalk.enabled = true;
	chalk.level = 4;
});
```

If you need your colored tests to pass on both Windows and Linux/Mac, you may still need to normalize the `process.platform` as chalk has some shims for color behavior under Windows. Something like this, perhaps.

```js
let originalPlatform;
beforeAll(function () {
	// The behavior of chalk differs based on the platform; for these tests, normalize the platform.
	originalPlatform = process.platform;
	Object.defineProperty(process, 'platform', { value: 'linux' });
});
afterAll(function () {
	// Restore the original platform.
	Object.defineProperty(process, 'platform', { value: originalPlatform });
});
```

You will also need to clear chalk out of the require cache after altering the `process.platform` so that the root module code runs again. If you're using Jest, that's a little more complicated than just:

```js
delete require.cache[require.resolve('chalk')];
```

You would have to use the `jest.resetModules()` function as Jest has taken control of the whole system and normal methods don't work. The downside to this is that it resets _everything_, so if you had previously required something (even something that's not the unit under test), those may have to be required again.

**Comment by Berkmann18** [comment]
@nazrhyn Did your test suits directly imported `chalk`?
Mine doesn't and I'm thinking it would be less hassle to have tested against whatever `chalk[...]` returns instead of testing the actual values (which change based on `chalk.level`).

**Comment by nazrhyn** [comment]
Our test suite for this project doesn't actually use **chalk** for coloring, though it does need a reference to it to turn coloring on and off. (Unfortunately, Jest _itself_ does use **chalk**; though, it's possible to work around that.) Here's the approach I ended up taking (specific to Jest's API, at this point; when we were talking, before, I was using mocha+chai+sinon+mock-require+nyc):

1. Before everything, override the `process.platform` to `'linux'` to avoid all of the windows-specific shims in the **chalk** code.
1. Run `jest.resetModules()` and re-require **chalk** and the module under test.
1. Create two `describe` blocks: one for **uncolored** and another for **colored**.
1. Within the **uncolored** block:
   1. Run `chalk.enabled = false; chalk.level = 0;` to disable colored output.
   1. Write the bulk of the tests in this block, testing only formatting, as in this example:

        ```js
        it('returns with options.success = true but no message or options.fields', function () {
            expect(formatting.formatServiceLog('SERVICE-NAME', 'Action', { success: true }))
                .toBe(`[SERVICE-NAME] Action: SUCCESS`);
        });
        ```
1. Within the **colored** block:
   1. Run `chalk.enabled = true; chalk.level = 4;` to enable colored output.
   1. Write only enough tests for this block to cover all of the possible coloring variations, using snapshots to verify as in this example (since the structure/format should already be covered in the **uncolored** tests):
        
        ```js
        it('returns with options.fields, options.success and message', function () {
            // We use a snapshot for this test as we already have explicit tests for the organizational
            //  formatting, above; this is just to ensure that our colors stay the same.
            expect(formatting.formatServiceLog(
                'SERVICE-NAME',
                'Action',
                'message-text',
                { success: true, fields: { fieldOne: 'field-one' } }
            ))
                .toMatchSnapshot();
        });
        ```
1. Restore the `process.platform` to its previous value.
1. Run `jest.resetModules()` and re-require **chalk** and the module under test in case other tests run after this group.

This set-up seems much cleaner than what I had before (previously I was verifying the colors _and_ the structure in each test), and it completely avoids the need to mock the **supports-color** module now that we know how to use both of those properties to actually enable and disable **chalk**.

Does that help?

**Comment by Qix-** [comment]
Hi, maintainer of Chalk here.

I'll answer things one by one, but first I'd like to point out that despite the moniker escapes have been given, they are not (very well) standardized by the ANSI. In reality, the codes Chalk emits in particular are an amalgamation of VT100, XTerm, and some widely accepted modern codes such as Truecolor escapes. In no way are the codes guaranteed to be the same even at the patch level.

> I'm pleased to see more test passing, I find it odd that the Hello logs are coloured as expected but some of the test cases still show up as uncoloured.

Can you supply repro steps, the platform, the value of your `TERM` variable (if not on Windows), and the name/version of your terminal emulator?

> I wonder how easy it would be to just fork chalk and rip out the support detection.

Very easy, though I don't see why that would be necessary. You can specify levels manually that override the detected colors. See https://github.com/chalk/chalk#chalklevel and https://github.com/chalk/chalk#chalkenabled.

(Reading further, I see you've already done this.)

I'm aware the API surrounding that isn't ideal, but please keep in mind chalk is trying to make the best of a rough situation: it's a package dealing with archaic, non-standard technology (ANSI escapes) and trying to defeat bitrot and tend to backwards compatibility made early on since Chalk is **very** old.

Believe me, if there was a way to improve the situation and not piss off even 1% of [the maintainers of 42,000 packages](https://www.npmjs.com/package/chalk?activeTab=dependents) I would have personally done so by now.

Always welcome to hear feedback in the [Chalk 3 discussion thread](https://github.com/chalk/chalk/issues/300).

> If you need your colored tests to pass on both Windows and Linux/Mac, you may still need to normalize the process.platform as chalk has some shims for color behavior under Windows. 

Yes, but this is not something we can or will ever specify or guarantee determinism for. If Windows came out tomorrow and changed all the escape codes (since, again, they are _not_ actively or holistically standardized by any standards body, regardless of their name), we would have to support it - and the codes would look different per-platform.

Shimming the platform is one way of doing things but you're still not protected against us changing codes even in patch releases - because, again, we do **not** standardize or guarantee the output of a call to any coloring function.

> Unfortunately, Jest itself does use chalk; though, it's possible to work around that.

Perhaps I'm missing the point here, but why does Jest using chalk make any difference here? You shouldn't be testing against the output of a test library.

---

Which brings me to a solution that might work.

```javascript
// test-chalk.js
function testChalk() {
	const chalk = require('chalk');

	function makeStyleObject(open = '', close = '') {
		const fn = (...args) => open + args.join(' ') + close;

		Object.getOwnPropertyNames(chalk.constructor.prototype).forEach(col => {
			if (col === 'constructor') return;

			const twoLevel = Boolean(!chalk[col]._styles || !chalk[col]._styles[0]);

			if (twoLevel) {
				fn[col] = (...outer) => makeStyleObject(
					open + `<${col}(${outer.join(',')})>`,
					`</${col}>` + close
				);
			} else {
				Object.defineProperty(fn, col, {
					get: () => makeStyleObject(
						open + `<${col}>`,
						`</${col}>` + close
					)
				});
			}
		});

		return fn;
	}

	return makeStyleObject();
}

const instance = testChalk();
instance.instance = testChalk;
instance.module = module;

instance.inject = () => {
	require.cache[require.resolve('chalk')] = module;
};

module.exports = instance;
```
```javascript
require('./test-chalk').inject();
const chalk = require('chalk');

console.log(chalk.red.bold("hello"));
console.log(chalk.inverse("hello"));
console.log(chalk.bold.bgBlue.rgb(255, 2, 3)("hello"));
```
```
<red><bold>hello</bold></red>
<inverse>hello</inverse>
<bold><bgBlue><rgb(255,2,3)>hello</rgb></bgBlue></bold>
```

Makes for easier testing and doesn't rely on the output of the chalk escapes, which would break otherwise.

**Comment by Berkmann18** [comment]
@nazrhyn That makes sense. My entire testing pipeline uses Linux (WSL on my machine and GNU/Linux on TravisCI) so I don't need to worry (at least for now) about using the workaround with `process.platform = 'linux'`.

You make a good point about testing most stuff under an _uncoloured_ `describe` and the colour-specific ones under a _coloured_ `describe` which could be a good way to test in `no-color`-like environments.

**Comment by Berkmann18** [comment]
@Qix- 
> > I'm pleased to see more test passing, I find it odd that the Hello logs are coloured as expected but some of the test cases still show up as uncoloured.

> Can you supply repro steps, the platform, the value of your TERM variable (if not on Windows), and the name/version of your terminal emulator?

I think this [TravisCI build](https://travis-ci.org/Berkmann18/nclr/jobs/506302935) would be a good example of reproduction for what you're looking for.

> I'm aware the API surrounding that isn't ideal, but please keep in mind chalk is trying to make the best of a rough situation: it's a package dealing with archaic, non-standard technology (ANSI escapes) and trying to defeat bitrot and tend to backwards compatibility made early on since Chalk is very old.

That's understandable given (as you rightly said) its age and the platforms it targets.
I wonder how that new terminal that Windows has pre-released is going to affect how colours/symbols/... are handled (hopefully in a more modern way).

> Believe me, if there was a way to improve the situation and not piss off even 1% of the maintainers of 42,000 packages I would have personally done so by now.

Wouldn't have a beta version aimed at improving situations, like this and then having those packages being tested with the new changes to see if it breaks anything (including the platform support range), be a good idea?

I'll try your solution and see how that turns out.

**Comment by Qix-** [comment]
> I wonder how that new terminal that Windows has pre-released is going to affect how colours/symbols/... are handled (hopefully in a more modern way).

The windows terminal expanding support - right now at least - is merely bringing the Windows terminal closer to feature parity of modern terminals. The biggest improvement yet is the addition of truecolor support (which also includes 256 color support), which Windows has been lacking since the command prompt was invented 🙄 

Unfortunately, terminal feature detection is still broken, but there is some movement going on behind the scenes between the maintainers of some of the more mainstream terminal emulators to bring this functionality up to modern standards.

I think terminal detection is some of the oldest software tech people take for granted and still use today that hasn't been updated or revamped. It's pretty much as old as Unix and hasn't changed much since then.

Poor feature detection is also the reason why `supports-color` is a kitchen sink of nonsense. To justify it a bit, consider this problem: there's no way to reliably detect if the thing we're writing to supports color. That is to say, the most basic of checks is `isatty(1)`, or "is stdout a TTY (interactive session)?"

This brings a multitude of problems - if you're piping to a file, or to `grep` or something, it's useful, but if you're inside a scripting environment or if the grep is just filtering out lines, then you still want color. There's no easy way to know in which situations we need to perform in a certain way.

Unfortunately, to address your original statement, I don't foresee Microsoft pioneering anything in terms of terminal modernization any time soon - and if they did, I can't imagine it being the _correct_ direction (they have a bad history with console-like technology and APIs).

> Wouldn't have a beta version aimed at improving situations, like this and then having those packages being tested with the new changes to see if it breaks anything (including the platform support range), be a good idea?

There's not really much to improve aside from what's planned for Chalk 3. If I could have my way, I'd remove all of the CLI flag handling - but I fear the community would riot. I think it's an intrusive anti-pattern that does way too much magic.

Also, at the scale Chalk is at, "beta" makes little difference. People are still using `"chalk": "*"` or whatever, or Node 0.12, and expect full compatibility. We've already bitten the bullet a bit by moving to modern, non-transpiled es6 for our releases, which pissed a **lot** of people off 💃. Just have to do these things slowly.

I did the same thing in `debug` about a year (maybe more?) ago and people are **still** complaining about it, even though it's the right thing to do.

**Comment by nazrhyn** [comment]
@Qix- 
> Yes, but this is not something we can or will ever specify or guarantee determinism for. [...]
>
> Shimming the platform is one way of doing things but you're still not protected against us changing codes even in patch releases - because, again, we do not standardize or guarantee the output of a call to any coloring function.

That's fine. I am not fooling myself into thinking that the way that my tests are written today will survive the test of time on _all_ fronts. What I need is normalization of behavior, and the method that I posted above achieves that, and does so without mocking **supports-color** and in a fairly simple way, so I'm happy for now!

>Perhaps I'm missing the point here, but why does Jest using chalk make any difference here? You shouldn't be testing against the output of a test library.

Not a big deal, but in most cases like this:

```
<module-under-test> --> <dependency>
```

When mocking out a dependency of the module under test, usually it's fine to (1) mock the dependency, then (2) require the module. In this case, Jest has already loaded **chalk** into the require cache, so I have to (1) mock the dependency, (2) remove **chalk** from the require cache, and then (3) require the module under test.

------

In the end, the look behind the veil has been interesting, but my goal here was to just come back and let @Berkmann18 know that I found something that worked for me on Linux, Windows and in CI containers.

Cheers!

**Comment by Qix-** [comment]
> In the end, the look behind the veil has been interesting, but my goal here was to just come back and let @Berkmann18 know that I found something that worked for me on Linux, Windows and in CI containers.

And I want to make sure that, since you've pinged me for my input, my opinion that **testing against ANSI escapes coming from chalk is the objectively wrong way to test**.

Cheers!

**Comment by nazrhyn** [comment]
@Qix- 
>And I want to make sure that, since you've pinged me for my input, my opinion as a maintainer of Chalk is that testing against ANSI escapes coming from chalk is the objectively wrong way to test.

For sure, and I agree! That's why I described removing colors from all but one of my tests, above.

**Comment by Berkmann18** [comment]
> The windows terminal expanding support - right now at least - is merely bringing the Windows terminal closer to feature parity of modern terminals. The biggest improvement yet is the addition of truecolor support (which also includes 256 color support), which Windows has been lacking since the command prompt was invented 🙄

That's what I was thinking as well.

Coming back on the `testChalk().inject`, it works fine on Node (v11.12) but once I try to test that in Jest it would still colour it without having the `<col>...</col>` being there (I tried, having the `require('./test-chalk').inject()` in `index.js` and the `lib.js` which supplies common functions to `index.js`/`symbols.js` and neither of them seem to be affected by the injection(s)).
You can see it on [this new branch](https://github.com/Berkmann18/nclr/tree/colour-fix).

Does that injection work within a jest test for you?

> > And I want to make sure that, since you've pinged me for my input, my opinion as a maintainer of Chalk is that testing against ANSI escapes coming from chalk is the objectively wrong way to test.

> For sure, and I agree! That's why I described removing colors from all but one of my tests, above.

It's definitely better to test with the names instead of that archaic and fairly cryptic colour system that *nix terminals have.

**Pull request merged**
